[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "panic=abort",
    "-C", "opt-level=s"
]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["panic_immediate_abort"]